[funfacts]
title = "Hacker News"
url = "https://news.ycombinator.com/news"
entrySelector = ".athing"              # top-level item rows on Hacker News
titleSelector = ".titleline a"         # title link in modern HN markup
linkSelector = ".titleline a"          # the same link element points to the article

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
